# Generated by Django 4.1.7 on 2023-03-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marvel_heroes', '0002_alter_heroes_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroes',
            options={'ordering': ['-time_create', 'title'], 'verbose_name': 'Hero', 'verbose_name_plural': 'Main heroes'},
        ),
    ]
